# @package _global_

task: classification

policy_model:
  task_factor: 0.1
  gp_factor: 10
  temperature: 0.05
  num_sub_policies: 10
  num_chunks: 8
  operation_count: 4

classification_model:
  num_classes: 10
  architecture: resnet18
  pretrained: false

data:
  dataset_file: dataset.py
  input_dtype: uint8
  preprocessing: null
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

  dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 16
    shuffle: true
    num_workers: 0
    pin_memory: true
    drop_last: true

optim:
  main:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0, 0.999]
  policy:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0, 0.999]
seed: 42

hydra:
  run:
    dir: ${config_dir:}/outputs
trainer:
  max_epochs: 1
  benchmark: true
  gpus: 0
callbacks:
- _target_: autoalbument.callbacks.MonitorAverageParameterChange
- _target_: autoalbument.callbacks.SavePolicy
logger: null
_version: 2
